name: Update Extension Zip

on:
  push:
    branches: [ master ]

jobs:
  update-zip:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed for git history
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y jq zip
        
    - name: Run zip script
      run: |
        chmod +x zip_extension.sh
        ./zip_extension.sh
        
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull --ff-only
        git push